<?php

namespace App\Domain\Shared\Enums;

enum AuditEventType: string
{
    case LOGIN = 'LOGIN';
    case LOGOUT = 'LOGOUT';
    case LOGIN_FAILED = 'LOGIN_FAILED';
    case WORK_ORDER_CREATED = 'WORK_ORDER_CREATED';
    case WORK_ORDER_UPDATED = 'WORK_ORDER_UPDATED';
    case CLAIM_CREATED = 'CLAIM_CREATED';
    case VERIFICATION_STARTED = 'VERIFICATION_STARTED';
    case AGENT_INVOKED = 'AGENT_INVOKED';
    case CAMARA_REQUEST = 'CAMARA_REQUEST';
    case EVIDENCE_RECEIVED = 'EVIDENCE_RECEIVED';
    case EVIDENCE_CONFLICT = 'EVIDENCE_CONFLICT';
    case ESCALATION = 'ESCALATION';
    case DECISION_CREATED = 'DECISION_CREATED';
    case DECISION_GUARD_APPLIED = 'DECISION_GUARD_APPLIED';
    case DECISION_OVERRIDDEN = 'DECISION_OVERRIDDEN';
    case REVIEW_CREATED = 'REVIEW_CREATED';
    case REVIEW_RESOLVED = 'REVIEW_RESOLVED';
    case POLICY_UPDATED = 'POLICY_UPDATED';
    case USER_CREATED = 'USER_CREATED';
    case USER_UPDATED = 'USER_UPDATED';
    case ORGANIZATION_CREATED = 'ORGANIZATION_CREATED';
    case ORGANIZATION_STATUS_CHANGED = 'ORGANIZATION_STATUS_CHANGED';
    case ADMIN_ACTION = 'ADMIN_ACTION';
    case AGENT_FAILURE = 'AGENT_FAILURE';
}
